# Use version 3 for compatibility
version: '3.8'

services:
   mysql:
      image: mysql:8.0
      container_name: mysql_db
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: rootpassword
         MYSQL_DATABASE: node-complete
         MYSQL_USER: user
         MYSQL_PASSWORD: userpassword
      ports:
         - "3306:3306"
      volumes:
         - node-complete:/var/lib/mysql

volumes:
   node-complete:
